# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ddd628e01d135147be16a0abb724e6bcbdf797c90ea20729aeacc5ceffd9aa49ed8be16413694fa1798a2a02f339aa2784ee0ce0563b798d8e901d5fef8f2e1

test:
  secret_key_base: e0ee78db92640429867f62181874b12c5d82485d44ac2503a208328ef85af15141c7394ed4a392a4b68f3e8a676c620d09674ad67bac8ee8527b9e31c15222d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
